# Instrument setup
# > 'accessories' > IADS > change from 'remove volatile/moisture compensation' to OFF
# > Control Panel > 


# Text file format Fidas:
header = ['Date',
'Time',
'Comment',
'PM1',
'PM2.5',
'PM4',        
'PM10',
'PMtotal',
'Number Concentration',
'Humidity',
'Temperature',
'Pressure',
'Flow',
'Coincidence',
'Pumps',
'Weather station',
'IADS',
'Calibration',
'LED',
'Operating mode',
'Device status',
'PM1',
'PM2.5',
'PM4',
'PM10',
'PMtotal',
'PM1_classic',
'PM2.5_classic',
'PM4_classic',
'PM10_classic',
'PMtotal_classic',
'PMthoraic',
'PMalveo',
'PMrespirable',
'Flowrate',
'Velocity',
'Coincidence',
'Pump_output',
'IADS_temperature',
'Raw channel deviation',
'LED temperature',
'Temperature*',
'Humidity*',
'Pressure*',]

device_status = {'Scope':0,
                 'Auto':1,
                 'Manual':2,
                 'Idle':3,
                 'Calib':4,
                 'Offset':5,
                 'PDControl':6,
                 }
