simulate: true

# local paths configuration
local:
  root: tests/results
  data: data                # specify folder relative to <root> directory
  staging: staging          # specify folder relative to <root> directory
  logging: logs             # specify folder relative to <root> directory

# logging configuration
logging:
  file_name: pydaq.log      # specify file relative to <logging> directory
  level_console: INFO
  level_file: ERROR

# data transfer configuration
transfer:
  protocol: sftp            # options: sftp, mqtt
  sftp:
    host: sftp.meteoswiss.ch
    usr: gaw_kenya
    key: ~/.ssh/private-open-ssh-4096-mkn.ppk
    remote_path: 'tests'    # remote path to store data
    proxy:
        socks5:             # proxy url (leave empty if no proxy is used)
        port: 1080
  mqtt:
    host: mqtt.example.com
    port: 1883
    qos: 1
    retain: false
    delay: 0.1
    topic: gaw_kenya/tests

# local serial ports configuration
ports:
  COM1:
    protocol: RS232             # don't change!
    baudrate: 9600
    bytesize: 8
    stopbits: 1
    parity: N
    timeout: 0.1                # seconds, how long to wait for a response
  COM2:
    protocol: RS232             # don't change!
    baudrate: 9600
    bytesize: 8
    stopbits: 1
    parity: N
    timeout: 0.1                # seconds, how long to wait for a response

# attached instruments configuration
instruments:
  - name: 49i
    class: instr.thermo.Thermo49i
    params:
      id: 49
      serial_number: #49I-B1NAA-12103910681
      communication: socket     # options: socket, serial
      # serial: COM1
      socket:
        mode: tcp           # options: tcp, udp
        host: 192.168.100.2
        port: 9880
        timeout: 5
        sleep: 0.1
      get_config:
        - date
        - time
        - mode
        - gas unit
        - temp comp
        - pres comp
        - range
        - format
        - avg time
        - lrec per
        - lrec format
        - o3 coef
        - o3 bkg
      set_config:
        - set mode remote
        - set gas unit ppb
        - set temp comp on
        - set pres comp on
        - set range 1
        - set format 00
        # - set avg time 1        # NB: implemented in init based on averaging_interval
        # - set lrec per 1        # NB: implemented in init based on averaging_interval
        - set lrec format 0
        - set save params
      get_data: lr00
      averaging_interval: 1       # minutes. NB: determines set avg time and set lrec per
      reporting_interval: 60      # minutes
      staging_zip: true

  # - name: fidas
  #   class: instruments.instrument_fidas.Fidas200TCP
  #   params:
  #     ip: 192.168.100.3
  #     port: 23
  #     output_interval: 600
  #     read_params: [60, 61, 64]
  #     setup_params: {}
  #     poll_interval: 60
