station:
  wsi: 0-20008-0-MKN
  id: mkn
  name: Mount Kenya (GAW Global Station)
  timezone: UTC

paths:
  root: ~/pydaq/mkn
  data: data
  outbox: outbox
  logs: logs

logging:
  file: pydaq.log
  level_console: info
  level_file: error

main:
  loop_sleep_seconds: 1
  config_reload_seconds: 60
  dashboard:
    enabled: true
    host: 0.0.0.0
    port: 8088

transfer:
  require_all_targets: false
  scan_every_seconds: 600
  retries: 3
  backoff_seconds: 2
  max_backoff_seconds: 30
  targets:
    s3:
      enabled: true
      parameters:
        endpoint_url: https://service.meteoswiss.ch/
        bucket: ch.meteoswiss.gawkenya
        prefix: mkn
        region: eu-central-1
        access_key_id: ~/.secrets/s3_access_key_id
        secret_access_key: ~/.secrets/s3_secret_access_key
        verify: true
        addressing_style: path
    sftp:
      enabled: true
      parameters:
        host: "sftp.example"
        user: "user"
        remote_base: "."
        key: "~/.ssh/id_rsa"
        port: 22

network_monitor:
  enabled: true
  interval_s: 60
  timeout_s: 1.0
  log_unchanged_every_n: 0

instruments:
  49c:
    enabled: false
    driver: thermo
    io: 
      kind: serial
      device: /dev/ttyusb0 
      baudrate: 9600 
      bytesize: 8 
      parity: n
      stopbits: 1
      timeout_seconds: 1 
    schedule:
      sample_every_seconds: 60
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 30
    output:
      format: csv_zip
      remote_path: tei49c
      remove_on_success: true
    init: {}
    processing: {}

  49i:
    enabled: false
    driver: thermo
    io: 
      kind: socket 
      host: 192.168.3.190
      port: 9880
      timeout: 5
      sleep: 0.5
    schedule:
      sample_every_seconds: 60
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 30
    output:
      format: csv_zip
      remote_path: tei49c
      remove_on_success: true
    init: {}
    processing: {}
