station:
  wsi: 0-20008-0-NRB
  id: nrb # must be exactly 3 characters, used in file naming and remote paths
  name: Nairobi (GAW Regional Station)
  timezone: UTC

paths:
  root: ~/Documents/nrb
  data: data
  outbox: outbox
  logs: logs

logging:
  file: pydaq.log
  level_console: info
  level_file: warning

main:
  loop_sleep_seconds: 1
  config_reload_seconds: 60
  dashboard:
    enabled: true
    host: 0.0.0.0
    port: 8088

transfer:
  require_all_targets: true # require successful transfer of all targets before emptying the outbox.
  scan_every_seconds: 600
  retries: 3
  backoff_seconds: 2
  max_backoff_seconds: 30
  targets:
    s3:
      enabled: true
      parameters:
        endpoint_url: https://service.meteoswiss.ch/
        bucket: ch.meteoswiss.gawkenya
        prefix: nrb/incoming
        region: eu-central-1
        access_key: ~/.secrets/s3_access_key
        secret_key: ~/.secrets/s3_secret_key
        verify: true
        addressing_style: path
    sftp:
      enabled: false
      parameters:
        host: sftp.meteoswiss.ch
        user: gaw_kenya
        remote_base: "./nrb"
        key: ~/.ssh/nrb-ed25519-20260508
        proxy:
            socks5:             # proxy url (leave empty if no proxy is used)
            port: 1080

network_monitor:
  enabled: true
  interval_s: 60
  timeout_s: 1.0
  log_unchanged_every_n: 0

instruments:
  49c:
    enabled: false
    driver: 49c
    io: 
      kind: serial
      device: /dev/ttyusb0 
      baudrate: 9600 
      bytesize: 8 
      parity: n
      stopbits: 1
      timeout_seconds: 1 
    schedule:
      sample_every_seconds: 60
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 0 # 0 means no printing to console
    output:
      format: csv_zip
      remote_path: 49c
      remove_on_success: true
    init: {}
    processing: {}

  49i:
    mac: 00-06-3B-20-36-A1
    id: 49
    serial_number: 49I-B1NAA-12103910681
    enabled: true
    driver: 49i
    io: 
      kind: socket 
      host: 192.168.2.14
      port: 9880
      timeout: 5
      sleep: 0.5
    schedule:
      sample_every_seconds: 60
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 0 # 0 means no printing to console
    output:
      format: csv_zip
      remote_path: 49i
      remove_on_success: true
    init: {}
    processing: {}

  fidas:
    # mac: 00-18-7D-2D-CA-84
    # serial_number: 6082
    enabled: true
    driver: FIDAS
    io:
      kind: udp
      host: 0.0.0.0 #192.168.2.223
      port: 56790
      buffer_size: 8192
      timeout: 0.5
      sleep: 0.5
    schedule:  
      sample_every_seconds: 5             # How often should data be read from instrument?
      aggregation_period_minutes: 1       # What aggregate of data should be stored?
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 0 # 0 means no printing to console
    output:
      format: csv_zip
      remote_path: fidas
      remove_on_success: true
    init: {}
    processing: {}

  ae31:
    enabled: true
    driver: ae31 #pydaq.instruments.magee.AE31
    id: 9440810
    serial_number: "944:0810"
    io:
      kind: serial
      device: /dev/ttyUSB2
      baudrate: 9600
      bytesize: 8
      parity: N
      stopbits: 1
      timeout_seconds: 270
    schedule:
      sample_every_seconds: 300
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 0 # 0 means no printing to console
    output:
      format: csv_zip
      remote_path: ae31
      remove_on_success: true
    init: {}
    processing: {}

  aurora3000:
    enabled: true
    driver: aurora3000
    protocol: aurora
    id: 0
    serial_number:
    io:
      kind: serial
      device: /dev/serial/by-id/usb-Moxa_Technologies_Co.__Ltd._UPort_1150-if00-port0
      baudrate: 19200
      bytesize: 8
      parity: N
      stopbits: 1
      timeout_seconds: 5
    schedule:
      sample_every_seconds: 5
      aggregation_period_minutes: 1
      aggregation_timestamp: end
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 0 # 0 means no printing to console
    output:
      format: csv_zip
      remote_path: aurora3000
      remove_on_success: true
    init: {}
    processing:
      aggregation_method: mean

  hmp110-inlet:
    enabled: true
    driver: hmpascii
    id: 1
    serial_number: U2110079  # aerosol inlet manyfold
    io:
      # kind: socket
      # host: 192.168.0.100
      # port: 5004
      kind: serial
      port: /dev/ttyUSB1
      baudrate: 19200 
      bytesize: 8 
      parity: N
      stopbits: 1
      timeout_seconds: 1 
      timeout: 5.0
      idle_timeout: 0.25
      sleep: 0.1
    schedule:
      sample_every_seconds: 5
      aggregation_period_minutes: 1
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 0 # 0 means no printing to console
    output:
      format: csv_zip
      remote_path: hmp110-inlet
      remove_on_success: true
    init:
      command_sequence:
        - "SEND {id}"

  hmp110-ae31:
    enabled: true
    driver: hmpascii
    id: 2
    serial_number: M4730288  # inlet AE31
    io:
      # kind: socket
      # host: 192.168.0.100
      # port: 5004
      kind: serial
      port: /dev/ttyUSB1
      baudrate: 19200 
      bytesize: 8 
      parity: N
      stopbits: 1
      timeout_seconds: 1 
      timeout: 5.0
      idle_timeout: 0.25
      sleep: 0.1
    schedule:
      sample_every_seconds: 5
      aggregation_period_minutes: 1
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 0 # 0 means no printing to console
    output:
      format: csv_zip
      remote_path: hmp110-ae31
      remove_on_success: true
    init:
      command_sequence:
        - "SEND {id}"

  hmp110-lab:
    enabled: true
    driver: hmpascii
    id: 3
    serial_number: U2110085  # inside lab near window
    io:
      # kind: socket
      # host: 192.168.0.100
      # port: 5004
      kind: serial
      port: /dev/ttyUSB1
      baudrate: 19200 
      bytesize: 8 
      parity: N
      stopbits: 1
      timeout_seconds: 1 
      timeout: 5.0
      idle_timeout: 0.25
      sleep: 0.1
    schedule:
      sample_every_seconds: 5
      aggregation_period_minutes: 1
      rollover: hourly
      rollover_at: ":00"
      transmit_every_seconds: 3600
      transmit_delay_seconds: 15
      print_every_seconds: 0 # 0 means no printing to console
    output:
      format: csv_zip
      remote_path: hmp110-lab
      remove_on_success: true
    init:
      command_sequence:
        - "SEND {id}"

  avo-roof:
    enabled: true
    driver: avo
    io:
      kind: http
      urls:
        roof: https://device.iqair.com/v2/64b79227b6f7b1125b019970
      validated: false
      timeout_seconds: 30
      retries: 3
      backoff_seconds: 2
      verify: true
    schedule:
      sample_every_seconds: 3600
      transmit_every_seconds: 3600
      transmit_delay_seconds: 60
    output:
      data_path: avo-roof
      staging_path: avo-roof
      remote_path: avo-roof
      remove_on_success: true
    processing:
      datasets:
        - instant
        - hourly
        - daily
        - monthly
      append: true
      remove_duplicates: true

  avo-garden:
    enabled: true
    driver: avo
    io:
      kind: http
      urls:
        garden: https://device.iqair.com/v2/66b49848bc7616df52bd5100  # "name": "KMD SENSOR HQ",
      validated: false
      timeout_seconds: 30
      retries: 3
      backoff_seconds: 2
      verify: true
    schedule:
      sample_every_seconds: 3600
      transmit_every_seconds: 3600
      transmit_delay_seconds: 60
    output:
      data_path: avo-garden
      staging_path: avo-garden
      remote_path: avo-garden
      remove_on_success: true
    processing:
      datasets:
        - instant
        - hourly
        - daily
        - monthly
      append: true
      remove_duplicates: true

  avo-huduma:
    enabled: true
    driver: avo
    io:
      kind: http
      urls:
        huduma: https://device.iqair.com/v2/64ad7a78e939e8f45b826839
      validated: false
      timeout_seconds: 30
      retries: 3
      backoff_seconds: 2
      verify: true
    schedule:
      sample_every_seconds: 3600
      transmit_every_seconds: 3600
      transmit_delay_seconds: 60
    output:
      data_path: avo-huduma
      staging_path: avo-huduma
      remote_path: avo-huduma
      remove_on_success: true
    processing:
      datasets:
        - instant
        - hourly
        - daily
        - monthly
      append: true
      remove_duplicates: true

  avo-mogogosiek:
    enabled: true
    driver: avo
    io:
      kind: http
      urls:
        mogogosiek: https://device.iqair.com/v2/64b78e3ed49ffdbbf25ce862
      validated: false
      timeout_seconds: 30
      retries: 3
      backoff_seconds: 2
      verify: true
    schedule:
      sample_every_seconds: 3600
      transmit_every_seconds: 3600
      transmit_delay_seconds: 60
    output:
      data_path: avo-mogogosiek
      staging_path: avo-mogigosiek
      remote_path: avo-mogogosiek
      remove_on_success: true
    processing:
      datasets:
        - instant
        - hourly
        - daily
        - monthly
      append: true
      remove_duplicates: true
